config/routes.rb
Rails.application.routes.draw do

  resources :product_exits, except: [:show]
  resources :product_entries, except: [:show]
  resources :products, except: [:show]
  resources :sellers, except: [:show]
  resources :suppliers, except: [:show]
  resources :subcategories, except: [:show]
  resources :categories, except: [:show]

  root to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true
end

app/models/product_balance.rb
class ProductBalance < ApplicationRecord
  belongs_to :product_entry
  belongs_to :product_exit
  belongs_to :product
end

app/models/product_entry.rb
class ProductEntry < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :supplier, optional: true
end

app/models/product_exit.rb
class ProductExit < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :seller, optional: true
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet">
    <link rel="shortcut icon" href="<%= asset_path('icon.png') %>" >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render partial: 'layouts/shared/navbar' %>
    <div id="main-wrapper">
      <div class="page-wrapper">
        <%= configure_and_display_flash_messages %>
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
  Loja Online
</footer>

app/views/layouts/shared/_header.html.erb
<header class="topbar hidden-sm-up">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
    <!-- ============================================================== -->
    <!-- Logo -->
    <!-- ============================================================== -->
    <div class="navbar-header">
      <a class="navbar-brand" href="index.html">
        <!-- Logo icon -->
        <b>
          <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
          <!-- Dark Logo icon -->
  <!--        <img src="../assets/images/logo-icon.png" alt="homepage" class="dark-logo" />-->
          <!-- Light Logo icon -->
  <!--        <img src="../assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />-->
        </b>
      </a>
      <!-- ============================================================== -->
      <!-- End Logo -->
      <!-- ============================================================== -->
      <div class="navbar-collapse">
        <!-- ============================================================== -->
        <!-- toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav mr-auto">
          <!-- This is  -->
          <li class="nav-item hidden-sm-up">
            <a class="nav-link nav-toggler waves-effect waves-light" href="javascript:void(0)">
              <i class="ti-menu"></i>
            </a>
          </li>
          <li class="nav-item hidden-sm-up">
            <a class="nav-link waves-effect waves-light" href="javascript:void(0)">
              Loja Online
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-app">
  <a class="navbar-brand" href="#">Vendas Online</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Dashboard', root_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Minhas Vendas', product_exits_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Minhas Pedidos', product_entries_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to sellers_path, class: 'nav-link' do %>
          <span class="hide-menu">Vendedores</span>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Configurações de Estoque
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Produtos', products_path, class: 'dropdown-item' %>
          <%= link_to 'Fornecedores', suppliers_path, class: 'dropdown-item' %>
          <%= link_to 'Categorias', categories_path, class: 'dropdown-item' %>
          <%= link_to 'Subcategorias', subcategories_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item">
        <div class="text-center">
          <%= link_to 'Sair', destroy_user_session_path, class: 'btn btn-danger' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/shared/_sidebar.html.erb
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar">
  <div class="d-flex no-block nav-text-box align-items-center">
    <span>
      Bem vindo, <%= current_user.name %>
    </span>
    <a class="waves-effect waves-dark ml-auto hidden-sm-down" href="javascript:void(0)">
      <i class="fa fa-bars"></i>
    </a>
    <a class="nav-toggler waves-effect waves-dark ml-auto hidden-sm-up" href="javascript:void(0)">
      <i class="fa fa-bars fa-close"></i>
    </a>
  </div>
  <!-- Sidebar scroll-->
  <div class="scroll-sidebar">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
      <ul id="sidebarnav">
        <li>
          <%= link_to root_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
            <span class="hide-menu">Dashboard</span>
          <% end %>
        </li>
        <li>
          <a class="has-arrow waves-effect waves-dark active" href="javascript:void(0)" aria-expanded="false">
            <i class="icon-speedometer"></i>
            <span class="hide-menu">Estoque</span>
          </a>
          <ul aria-expanded="false" class="collapse in">
            <li>
              <%= link_to product_exits_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Saida de Produtos</span>
              <% end %>
            </li>
            <li>
              <%= link_to product_entries_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Entrada de Produtos</span>
              <% end %>
            </li>
            <li>
              <%= link_to products_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Produtos</span>
              <% end %>
            </li>
            <li>
              <%= link_to suppliers_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Fornecedores</span>
              <% end %>
            </li>
            <li>
              <%= link_to categories_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Categorias</span>
              <% end %>
            </li>
            <li>
              <%= link_to subcategories_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
                <span class="hide-menu">Subcategorias</span>
              <% end %>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to sellers_path, class: 'waves-effect waves-dark', 'aria-expanded': 'false' do %>
            <span class="hide-menu">Vendedores</span>
          <% end %>
        </li>
        <div class="text-center m-t-30">
          <%= link_to 'Sair', destroy_user_session_path, style:"width: 50%;",
                      class: 'btn waves-effect waves-light btn-danger', 'aria-expanded': 'false' %>
        </div>
      </ul>
    </nav>
    <!-- End Sidebar navigation -->
  </div>
  <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja Online</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="shortcut icon" href="<%= asset_path('icon.png') %>" >
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'unauthenticated', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body class="skin-default card-no-border">
  <!-- ============================================================== -->
  <!-- Main wrapper - style you can find in pages.scss -->
  <!-- ============================================================== -->
  <section id="wrapper">
    <div class="login-register">
      <div class="login-box card">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </section>
</body>
</html>