config/routes.rb
Rails.application.routes.draw do

  resources :product_exits, except: [:show]
  resources :product_entries, except: [:show]
  resources :products, except: [:show]
  resources :sellers, except: [:show]
  resources :suppliers, except: [:show]
  resources :subcategories, except: [:show]
  resources :categories, except: [:show]

  root to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true
end

app/models/product_balance.rb
class ProductBalance < ApplicationRecord
  belongs_to :product_entry
  belongs_to :product_exit
  belongs_to :product
end

app/models/product_entry.rb
class ProductEntry < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :supplier, optional: true
end

app/models/product_exit.rb
class ProductExit < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :seller, optional: true
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/product_exits_controller.rb
class ProductExitsController < ApplicationController
  before_action :set_product_exit, only: [:edit, :update, :destroy]

  def index
    @product_exits = ProductExit.all
  end

  def new
    @product_exit = ProductExit.new
  end

  def edit
  end

  def create
    @product_exit = ProductExit.new(product_exit_params)
    create_crud(@product_exit, product_exit_path)
  end

  def update
    update_crud(@product_exit, product_exit_params, product_exit_path)
  end

  def destroy
    destroy_crud(@product_exit, product_exit_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_exit
      @product_exit = ProductExit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_exit_params
      params.require(:product_exit).permit(:amount, :price, :observation, :comission, :product_id, :seller_id)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/product_exits_helper.rb
module ProductExitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/product_exits/_form.html.erb
<%= form_with(model: product_exit, local: true) do |form| %>
  <% if product_exit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_exit.errors.count, "error") %> prohibited this product_exit from being saved:</h2>

      <ul>
        <% product_exit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :observation %>
    <%= form.text_field :observation %>
  </div>

  <div class="field">
    <%= form.label :comission %>
    <%= form.text_field :comission %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :seller_id %>
    <%= form.text_field :seller_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_exits/edit.html.erb
<h1>Editing Product Exit</h1>

<%= render 'form', product_exit: @product_exit %>

<%= link_to 'Show', @product_exit %> |
<%= link_to 'Back', product_exits_path %>

app/views/product_exits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Exits</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Price</th>
      <th>Observation</th>
      <th>Comission</th>
      <th>Product</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_exits.each do |product_exit| %>
      <tr>
        <td><%= product_exit.amount %></td>
        <td><%= product_exit.price %></td>
        <td><%= product_exit.observation %></td>
        <td><%= product_exit.comission %></td>
        <td><%= product_exit.product_id %></td>
        <td><%= product_exit.seller_id %></td>
        <td><%= link_to 'Show', product_exit %></td>
        <td><%= link_to 'Edit', edit_product_exit_path(product_exit) %></td>
        <td><%= link_to 'Destroy', product_exit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Exit', new_product_exit_path %>

app/views/product_exits/new.html.erb
<h1>New Product Exit</h1>

<%= render 'form', product_exit: @product_exit %>

<%= link_to 'Back', product_exits_path %>

app/views/product_exits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @product_exit.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product_exit.price %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @product_exit.observation %>
</p>

<p>
  <strong>Comission:</strong>
  <%= @product_exit.comission %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_exit.product_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @product_exit.seller_id %>
</p>

<%= link_to 'Edit', edit_product_exit_path(@product_exit) %> |
<%= link_to 'Back', product_exits_path %>