config/routes.rb
Rails.application.routes.draw do

  resources :product_exits, except: [:show]
  resources :product_entries, except: [:show]
  resources :products, except: [:show]
  resources :sellers, except: [:show]
  resources :suppliers, except: [:show]
  resources :subcategories, except: [:show]
  resources :categories, except: [:show]

  root to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true
end

app/models/product_balance.rb
class ProductBalance < ApplicationRecord
  belongs_to :product_entry
  belongs_to :product_exit
  belongs_to :product
end

app/models/product_entry.rb
class ProductEntry < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :supplier, optional: true
end

app/models/product_exit.rb
class ProductExit < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :seller, optional: true
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    create_crud(@category, categories_path)
  end

  def update
    update_crud(@category, category_params, categories_path)
  end

  def destroy
    destroy_crud(@category, categories_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_header_helper(page_title, page_path = [], button = nil)
    html = ''
    html << " <div class='row page-titles'>"
    html << "   <div class='col-sm-5 align-self-center'>"
    html << "     <h4 class='text-themecolor'>#{page_title}</h4>"
    html << "   </div>"
    html << "   <div class='col-sm-7 align-self-center text-right'>"

    if page_path.length != 0
      html << "   <div class='d-flex justify-content-end align-items-center force-flexbox breadcrumb-navigator'>"
      html << "     <ol class='breadcrumb'>"

      page_path.each do |element|
        if element != page_path.last
          html << "   <li class='breadcrumb-item'>"
          html << "     <a href='#{element[:link]}'>#{element[:name]}</a>"
          html << "   </li>"
        else
          html << "   <li class='breadcrumb-item active'>#{element[:name]}</li>"
        end
      end

      html << "     </ol>"
    end

    unless button.nil?
      html << "     <a href='#{button[:link]}' class='#{button[:class]}'>"
      html << "       #{button[:content].html_safe}"
      html << "     </a>"
    end

    html << "     </div>"
    html << "   </div>"
    html << " </div>"
    html.html_safe
  end

  def configure_and_display_flash_messages
    html = ''
    unless flash[:notice].nil? && flash[:error].nil?
      html << mount_flash_message_html
    end
    html.html_safe
  end

  def mount_flash_message_html
    if flash[:notice]
      message = flash[:notice]
      type = 'alert-success'
    else
      message = flash[:error]
      type = 'alert-danger'
    end

    html = "<div class='alert #{type} alert-dismissible fade show' role='alert'>#{message}"
    html << ' <button type="button" class="close" data-dismiss="alert" aria-label="Close">'
    html << '   <span aria-hidden="true">&times;</span>'
    html << ' </button>'
    html << '</div>'
    html
  end

  def format_price(price)
    number_to_currency(price, delimiter: :'', separator: :',', precision: 2, unit: :'R$ ')
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/categories/_form.html.erb
<% if category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <%= form_with(model: category, method:'post', url: url, local: true, class:'form-material') do |f| %>
          <%= hidden_field_tag :id, category.id %>

          <div class="row">
            <div class="form-group col-md-8">
              <%= f.label :description, "Descrição" %><br />
              <%= f.text_field :description, class: 'form-control form-control-line' %>
            </div>
          </div>

          <div class="form-group">
            <%= link_to 'Voltar', products_path, class: 'btn btn-secondary waves-effect waves-light m-r-10' %>
            <%= button_tag "Salvar", class: 'btn btn-info waves-effect waves-light m-r-10' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<%
  page_title = 'Editar Categoria'
  page_path = [
      { name: 'Inicio', link: root_path },
      { name: 'Editar Categoria', link: '' },
  ]
%>
<%= page_header_helper(page_title, page_path) %>
<%= render 'form', category: @category, url: categories_edit_path %>

app/views/categories/index.html.erb
<%
  page_title = "Categorias"
  page_path = [
      { name: 'Inicio', link: root_path },
      { name: 'Categorias', link: root_path },
  ]
  button = {
      link: new_category_path,
      class: 'btn btn-info m-l-15',
      content: '<i class="fa fa-plus-circle"></i> Criar'.html_safe
  }
%>
<%= page_header_helper(page_title, page_path, button) %>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Descrição</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
            <% if @categories.length > 0 %>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.description %></td>
                  <td width="10">
                    <%= link_to edit_category_path(category), class: 'btn btn-sm btn-outline-info',
                                'data-toggle': "tooltip", 'data-placement':"bottom", title: "Editar" do %>
                      <i class="fa fa-edit"></i>
                    <% end %>
                  </td>
                  <td width="10">
                    <%= link_to category, class: "btn btn-sm btn-danger",
                                method: :delete, data: { confirm: 'Deseja excluir essa categoria?' },
                                'data-toggle': "tooltip", 'data-placement':"bottom", title: "Excluir" do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td colspan="10">
                  <h6 class="card-subtitle card-subtitle-no-result">
                    Nenhuma categoria foi encontrada.
                  </h6>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%
  page_title = 'Nova Categoria'
  page_path = [
      { name: 'Inicio', link: root_path },
      { name: 'Nova Categoria', link: '' },
  ]
%>
<%= page_header_helper(page_title, page_path) %>
<%= render 'form', category: @category, url: categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>